service_plus/apps/documents/urls.py
from django.conf.urls import url

from documents import views as docs_views


urlpatterns = [
    url(r'^(?P<pk>\d+)/receipt/$', docs_views.BaseDocumentView.as_view(
            template_name='documents/receipt.odt', output_format='pdf',
            visible_filename='receipt.pdf'),
        name='receipt'),
    url(r'^(?P<pk>\d+)/guarantee/$', docs_views.BaseDocumentView.as_view(
            template_name='documents/guarantee.odt', output_format='pdf',
            visible_filename='guarantee.pdf'),
        name='guarantee'),
]

service_plus/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic import RedirectView, TemplateView

from rest_framework import routers

from crm import views as crm_views


router = routers.DefaultRouter()
router.register(r'jobs', crm_views.JobViewSet)
router.register(r'spare_part', crm_views.SparePartViewSet)
router.register(r'spare_part_count', crm_views.SparePartCountViewSet)

urlpatterns = [
    url(r'^$', crm_views.FrontpageView.as_view(), name='index'),
    url(r'^robots.txt$',
        TemplateView.as_view(template_name='robots.txt',
                             content_type='text/plain')),
    url(r'^favicon.ico$',
        RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'),
                             permanent=True)),
    url(r'^admin/docs/', include('documents.urls', namespace='documents')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^1c/', include('odinass.urls', namespace='1c')),
    url(r'^api/', include(router.urls)),
    url(r'^autocomplete/brand/$',
        login_required(crm_views.BrandAutocomplete.as_view()),
        name='brand-autocomplete',),
    url(r'^autocomplete/model/$',
        login_required(crm_views.ModelAutocomplete.as_view()),
        name='model-autocomplete',),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service_plus/apps/crm/models/booking.py
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.db.models.functions import Now

from dateutil.relativedelta import relativedelta

from django_fsm import FSMField, transition

from model_utils.models import TimeStampedModel

__all__ = (
    'Booking',
    'Guarantee',
    'State',
)


class State(object):
    """
    Содержит статусы заявки
    """
    CLIENT_ABORT = 'client_abort'
    FOR_PAYMENT = 'for_payment'
    PAYED = 'payed'
    WAITING_FOR_APPROVAL = 'waiting_for_approval'
    WAITING_FOR_PARTS = 'waiting_for_parts'
    WITHOUT_REPAIR = 'without_repair'
    WORKING = 'working'

    CHOICES = (
        (CLIENT_ABORT, 'отказ клиента'),
        (FOR_PAYMENT, 'на оплату'),
        (PAYED, 'оплачено клиентом'),
        (WAITING_FOR_APPROVAL, 'ждем подтверждения клиента'),
        (WAITING_FOR_PARTS, 'ждем запчасти'),
        (WITHOUT_REPAIR, 'без ремонта'),
        (WORKING, 'в работе'),
    )


class Guarantee(models.Model):
    """
    Гарантия по заявке
    """
    title = models.CharField(
        'название',
        max_length=254, db_index=True)

    day = models.PositiveSmallIntegerField(
        'дней',
        blank=True, null=True)

    month = models.PositiveSmallIntegerField(
        'месяцев',
        blank=True, null=True)

    year = models.PositiveSmallIntegerField(
        'лет',
        blank=True, null=True)

    order = models.PositiveIntegerField(
        u'порядок',
        default=0)

    class Meta:
        default_related_name = 'guarantees'
        ordering = ['order']
        verbose_name = 'гарантия'
        verbose_name_plural = 'гарантии'

    def __str__(self):
        return self.title

    @property
    def relative_data(self):
        """
        Промежуток времени, когда длится гарантия
        """
        return relativedelta(day=self.day, month=self.month, year=self.year)


class Booking(TimeStampedModel):
    """
    Клиентская заявка
    """
    state = FSMField(
        'статус',
        default=State.WORKING, choices=State.CHOICES, protected=True)

    client = models.ForeignKey(
        'crm.Client',
        verbose_name='клиент',
        on_delete=models.SET_NULL,
        blank=True, null=True)

    client_name = models.CharField(
        'ФИО',
        help_text='Фамилия Имя Отчество',
        max_length=254)

    client_address = models.CharField(
        'адрес',
        blank=True, max_length=254)

    client_characteristic = models.CharField(
        'характеристика/внешний вид',
        blank=True, max_length=254)

    client_email = models.EmailField(
        'email',
        blank=True)

    client_phone = models.CharField(
        'телефон',
        blank=True, max_length=254)

    imei = models.CharField(
        'IMEI',
        blank=True, max_length=30)

    brand = models.ForeignKey(
        'crm.Brand',
        verbose_name='бренд',
        on_delete=models.SET_NULL,
        blank=True, null=True)

    model = models.ForeignKey(
        'crm.Model',
        verbose_name='модель',
        on_delete=models.SET_NULL,
        blank=True, null=True)

    has_device = models.BooleanField(
        'устройство',
        default=True)

    has_battery = models.BooleanField(
        'аккумулятор',
        default=True)

    has_charger = models.BooleanField(
        'зарядное устройство',
        default=False)

    has_memory_card = models.BooleanField(
        'карта памяти',
        default=False)

    has_sim = models.BooleanField(
        'SIM-карта',
        default=False)

    has_bag_cover = models.BooleanField(
        'сумка/чехол',
        default=False)

    additional_kit = models.CharField(
        'дополнительно',
        blank=True, max_length=254)

    problem = models.TextField(
        'неисправность')

    note = models.CharField(
        'примечание',
        blank=True, max_length=254)

    estimated_date = models.DateField(
        'предполагаемая дата готовности')

    ready_date = models.DateTimeField(
        'дата готовности',
        blank=True, null=True, editable=False)

    close_date = models.DateTimeField(
        'дата выдачи',
        blank=True, null=True, editable=False)

    is_urgently = models.BooleanField(
        'срочно',
        default=False)

    estimated_cost = models.IntegerField(
        'предполагаемая стоимость')

    done_work = JSONField(
        'выполненная работа',
        blank=True, null=True)

    guarantee = models.ForeignKey(
        'crm.Guarantee',
        verbose_name='гарантия',
        on_delete=models.SET_NULL,
        blank=True, null=True)

    master = models.ForeignKey(
        'auth.User',
        verbose_name='мастер',
        on_delete=models.SET_NULL,
        limit_choices_to={'groups__name': 'Мастер'},
        blank=True, null=True)

    spare_parts = models.ManyToManyField(
        'crm.SparePart',
        verbose_name='запчасти',
        through='SparePartCount')

    gain = models.PositiveIntegerField(
        'полученные деньги',
        default=0, blank=True, null=True)

    replacement_device = models.OneToOneField(
        'crm.ReplacementDevice',
        verbose_name='устройство на замену',
        on_delete=models.SET_NULL,
        blank=True, null=True)

    class Meta:
        default_related_name = 'bookings'
        ordering = ['-pk']
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'

    def __str__(self):
        return str(self.pk)

    @transition(field=state, source=State.WORKING,
                target=State.WAITING_FOR_APPROVAL)
    def wait_agree(self, user=None):
        """
        Согласовать детали ремонта
        """

    @transition(field=state, source=State.WORKING,
                target=State.WAITING_FOR_PARTS)
    def wait_parts(self, user=None):
        """
        Ждать запчасти
        """

    @transition(field=state, source=State.WORKING, target=State.WITHOUT_REPAIR)
    def reject(self, user=None):
        """
        Ремонт не требуется или невозможен
        """

    @transition(field=state, source=State.WORKING, target=State.FOR_PAYMENT)
    def ready(self, user=None):
        """
        Готов к выдачи
        """
        if not self.master:
            groups_name = [name for name in user.groups.values_list('name',
                                                                    flat=True)]
            if 'Мастер' in groups_name:
                self.master = user
        self.ready_date = Now()

    def can_close(self):
        replacement_device = False if self.replacement_device else True
        money = self.debt == 0
        return all([replacement_device, money])

    @transition(field=state, source=[State.FOR_PAYMENT, State.WITHOUT_REPAIR],
                target=State.PAYED, conditions=[can_close])
    def close(self, user=None):
        """
        Закрыть заявку
        """
        self.close_date = Now()

    def can_repair(self):
        return self.state != 'working'

    @transition(field=state, source='*', target=State.WORKING,
                conditions=[can_repair])
    def repair(self, user=None):
        """
        Вернуть в ремонт
        """
        self.ready_date = None
        self.close_date = None

    @property
    def kit(self):
        """
        Полная комплектация
        """
        device = 'устройство' if self.has_device else None
        battery = 'аккумулятор' if self.has_battery else None
        charger = 'зарядное устройство' if self.has_charger else None
        memory_card = 'карта памяти' if self.has_memory_card else None
        sim = 'SIM-карта' if self.has_sim else None
        bag_cover = 'сумка/чехол' if self.has_bag_cover else None
        return ', '.join(filter(None, [device, battery, charger, memory_card,
                                       sim, bag_cover, self.additional_kit]))

    @property
    def available_transitions(self):
        """
        Доступные статусы
        """
        return [tr.name for tr in self.get_available_state_transitions()]

    @property
    def done_work_sum(self):
        done_work_sum = 0
        if self.done_work:
            done_work_sum = sum(job['price'] for job in self.done_work)
        return done_work_sum

    @property
    def spare_part_sum(self):
        return sum(self.spare_part_counts.values_list('retail_price',
                                                      flat=True))

    @property
    def total_sum(self):
        return self.done_work_sum + self.spare_part_sum

    @property
    def debt(self):
        return self.total_sum - self.gain

    @property
    def guarantee_items(self):
        items = []
        for item in self.spare_part_counts.all():
            items.append({
                'title': item.title,
                'price': item.retail_price or '',
                'guarantee': item.guarantee or '',
            })

        for item in self.done_work:
            items.append({
                'title': item['title'],
                'price': item['price'] or '',
                'guarantee': self.guarantee or '',
            })

        return items

service_plus/apps/crm/forms.py
from django import forms
from django.db.models import Q

from crm.models import Booking, State


class BaseBookingForm(forms.ModelForm):
    """
    Базовый класс формы заявки
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.change_field_attribute(
            'master', 'label_from_instance', self.master_label)
        self.change_field_attribute(
            'replacement_device', 'queryset',
            self.available_replacement_device())

    @staticmethod
    def master_label(obj):
        """
        Показываем фамилию и имя вместо логина
        """
        name = ' '.join(filter(None, [obj.last_name, obj.first_name]))
        if not name:
            name = obj.username
        return name

    def available_replacement_device(self):
        qs = self.fields['replacement_device'].queryset.filter(
            Q(booking__isnull=True) | Q(booking=self.instance))
        return qs

    def change_field_attribute(self, field_name, attribute, value):
        field = self.fields.get(field_name)
        if field:
            setattr(field, attribute, value)
        return field

    def change_fields_attribute(self, fields_name, attribute, value):
        fields = []
        for field_name in fields_name:
            fields.append(
                self.change_field_attribute(field_name, attribute, value))
        return fields


class BookingForm(BaseBookingForm):
    class Meta:
        model = Booking

        fields = (
            'done_work',
            'guarantee',
            'master',
            'replacement_device',
        )

        widgets = {
            'done_work': forms.HiddenInput,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.state == State.WORKING:
            self.change_fields_attribute(['guarantee', 'master', 'done_work'],
                                         'disabled', True)

    def clean_done_work(self):
        def price_to_int(obj):
            if 'price' in obj:
                obj['price'] = int(obj['price'])
            return obj
        data = self.cleaned_data['done_work']
        if data:
            data = list(map(lambda obj: price_to_int(obj), data))
        transition = self.data.get('transition')
        if self.instance.state == State.WORKING:
            if transition == 'ready' and not data:
                raise forms.ValidationError(
                    'Необходимо заполнить выполненную работу')
        return data

service_plus/apps/crm/views.py
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.views.generic import RedirectView

from dal import autocomplete

from rest_framework import status, viewsets
from rest_framework.response import Response

from crm.filters import SparePartCountFilterSet, SparePartFilterSet
from crm.models import Brand, Job, Model, SparePart, SparePartCount
from crm.serializers import (
    JobSerializer,
    SparePartCountSerializer,
    SparePartSerializer,
)


class FrontpageView(RedirectView):
    """
    Редирект на список задач
    """
    def get_redirect_url(self, *args, **kwargs):
        tasks_url = reverse('admin:crm_booking_changelist')
        if self.request.user.is_authenticated():
            url = tasks_url
        else:
            url = reverse('admin:login') + '?next=%s' % tasks_url
        return url


class BrandAutocomplete(autocomplete.Select2QuerySetView):
    """
    Автокомплит бренда по его полному названию
    """
    def get_queryset(self):
        qs = Brand.objects.all()
        if self.q:
            qs = qs.filter(name__icontains=self.q)
        return qs


class ModelAutocomplete(autocomplete.Select2QuerySetView):
    """
    Автокомплит моделей устройств по их названию, а так же фильтр по бренду
    """
    def get_queryset(self):
        brand = self.forwarded.get('brand', None)
        qs = Model.objects.all()
        if not brand:
            qs = qs.none()
        else:
            qs = qs.filter(name__icontains=self.q, brand=brand)
        return qs


class JobViewSet(viewsets.ModelViewSet):
    """
    Список предоставляемых работ с ценой
    """
    queryset = Job.objects.all()
    serializer_class = JobSerializer


class SparePartCountViewSet(viewsets.ModelViewSet):
    """
    Запчасти
    """
    filter_class = SparePartCountFilterSet
    model = SparePartCount
    queryset = SparePartCount.objects.select_related('booking')
    serializer_class = SparePartCountSerializer

    def destroy(self, request, pk=None):
        obj = self.get_object()
        spare_part, created = SparePart.objects.get_or_create(
            title=obj.title, brand=obj.brand, model=obj.model,
            purchase_price=obj.purchase_price, retail_price=obj.retail_price)
        obj.booking = None
        obj.spare_part = spare_part
        obj.save()
        return Response({'status': 'SparePart update'},
                        status=status.HTTP_200_OK)

    def filter_queryset(self, queryset):
        if self.action == 'list':
            booking_filter = self.request.GET.get('booking')
            if not booking_filter:
                queryset = queryset.none()
        return super().filter_queryset(queryset)


class SparePartViewSet(viewsets.ModelViewSet):
    """
    Запчасти
    """
    filter_class = SparePartFilterSet
    model = SparePart
    queryset = (SparePart.objects.select_related('brand', 'model')
                                 .prefetch_related('spare_part_counts')
                                 .annotate(count=Count('spare_part_counts'))
                                 .filter(count__gte=1))
    serializer_class = SparePartSerializer

    def update(self, request, pk=None):
        obj = self.get_object()
        spare_part_count = obj.spare_part_counts.last()
        (SparePartCount.objects.filter(pk=spare_part_count.pk)
                               .update(booking_id=request.data['booking'],
                                       spare_part=None))
        return Response({'status': 'SparePartCount update'},
                        status=status.HTTP_200_OK)

service_plus/apps/crm/templates/crm/admin/booking_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls static admin_list crm_tags %}

{% block filters %}
    <div class="actions goto-booking">
        <form action="goto/" method="POST">{% csrf_token %}
            <label>
                Номер заявки:
                <input type="text" name="booking" id="booking">
            </label>
            <button class="button" type="submit">Открыть</button>
        </form>
    </div>
    {{ block.super }}
{% endblock %}

{% block result_list %}
    {% if action_form and actions_on_top and cl.show_admin_actions %}{% admin_actions %}{% endif %}
    {% result_list cl %}
    {% if action_form and actions_on_bottom and cl.show_admin_actions %}{% admin_actions %}{% endif %}
{% endblock %}

service_plus/apps/crm/templates/crm/admin/booking_review.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static crm_tags pipeline %}

{% block title %}Просмотр заявки № {{ object.pk }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block extrahead %}{{ block.super }}
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    {{ media }}
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
    {% stylesheet 'fontawesome' %}
{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} review-form{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>
&rsaquo; Просмотр заявки № {{ object|truncatewords:"18" }}
</div>
{% endblock %}


{% block messages %}
    {{ block.super }}
    {% with object.available_transitions as transitions %}
        {% if transitions and object.state == 'for_payment' and 'close' not in transitions %}
        <ul class="messagelist">
            <li class="warning">Нельзя закрыть заявку, т.к. клиент не оплатил полную стоимость или не вернул устройство на замену!</li>
        </ul>
        {% endif %}
    {% endwith %}
{% endblock messages %}


{% block content %}
    <form action="" method="POST" data-csrf="{{ token.value }}">{% csrf_token %}{{ form.non_field_errors }}
    <div id="content-main">
        <fieldset class="module intro">
            <div class="field-box">
                <strong>Принят:</strong> {{ object.created }}
            </div>

            <div class="field-box">
                <strong>Предполагаемая дата готовности:</strong> {{ object.estimated_date }} {% if object.is_urgently %}(<span class="is_urgently">Срочно!</span>){% endif %}
            </div>

            <div class="field-box">
                <strong>Предполагаемая стоимость:</strong> {{ object.estimated_cost|price }}
            </div>
        </fieldset>

        {% if object.state == 'working' or object.state == 'payed' %}
        <fieldset class="module intro">
            <div class="field-box">
                <strong>Документы:</strong> {% if object.state == 'working' %}<a href="{% url 'documents:receipt' object.pk %}">Квитанция о приёме</a>{% endif %} {% if object.state == 'payed' %}<a href="{% url 'documents:guarantee' object.pk %}">Гарантийный талон</a>{% endif %}
            </div>
        </fieldset>
        {% endif %}

        <div class="side-left">
            {# CLIENT #}
            <div class="module aligned panel panel-client">
                <h2>Клиент</h2>
                <div class="form-row">
                    <label>ФИО</label>
                    <p>{{ object.client_name }}
                    {% if booking.client_characteristic %}
                        ({{ booking.client_characteristic }})
                    {% endif %}</p>
                </div>

                {% if object.client_phone %}
                    <div class="form-row">
                        <label>Телефон</label>
                        <p>{{ object.client_phone }}</p>
                    </div>
                {% endif %}

                {% if object.client_email %}
                    <div class="form-row">
                        <label>Email</label>
                        <p><a href="mailto:{{ object.client_email }}">{{ object.client_email }}</a></p>
                    </div>
                {% endif %}

                {% if object.client_address %}
                    <div class="form-row">
                        <label>Адрес</label>
                        <p>{{ object.client_address }}</p>
                    </div>
                {% endif %}
            </div>
            {# ------ #}

            {# DEVICE #}
            <div class="module aligned panel panel-device">
                <h2>Устройство</h2>
                {% if object.imei %}
                    <div class="form-row">
                        <label>IMEI</label>
                        <p>{{ object.imei }}</p>
                    </div>
                {% endif %}

                {% if object.brand or object.model %}
                    <div class="form-row">
                        <label>Модель</label>
                        <p id="device-model" data-brand="{{ object.brand_id }}" data-model="{{ object.model_id }}">{{ object.brand }} {{ object.model }}</p>
                    </div>
                {% endif %}

                {% if object.kit %}
                    <div class="form-row">
                        <label>Комплект</label>
                        <p>{{ object.kit }}</p>
                    </div>
                {% endif %}
            </div>
            {# ------ #}

            {# TOTAL #}
            <div class="module aligned panel panel-total">
                <h2>Итого</h2>
                <div class="form-row">
                    <label>Устройство на замену</label>
                    <p class="form-field">
                        {{ form.replacement_device.errors }}
                        {{ form.replacement_device }}
                    </p>
                </div>
                <div class="form-row">
                    <label>Гарантия на работу</label>
                    <p class="form-field">
                        {{ form.guarantee.errors }}
                        {{ form.guarantee }}
                    </p>
                </div>
                <div class="form-row">
                    <label>Мастер</label>
                    <p class="form-field">
                        {{ form.master.errors }}
                        {{ form.master }}
                    </p>
                </div>
                <div class="form-row">
                    <label>Сумма за ремонт</label>
                    <p id="booking-full-price">{{ object.total_sum|price }}</p>
                </div>
                <div class="form-row">
                    <label>Приход</label>
                    <p>{{ object.gain|price }}</p>
                </div>
                <div class="form-row">
                    <label>Долг</label>
                    <p>{{ object.debt|price }}</p>
                </div>
            </div>
            {# --------- #}
        </div>

        <div class="side-right">

            {# PROBLEM #}
            <div class="module aligned panel panel-problem">
                <h2>Неисправность</h2>
                {% if object.problem %}
                    <div class="form-row">
                        <label>Со слов клиента</label>
                        {{ object.problem|linebreaks }}
                    </div>
                {% endif %}

                {% if object.note %}
                    <div class="form-row">
                        <label>Примечание</label>
                        <p>{{ object.note }}</p>
                    </div>
                {% endif %}
            </div>
            {# ------- #}

            {# WORK DONE #}
            <div class="module aligned panel panel-done">
                <h2>Выполненная работа</h2>
                <div class="form-row">
                    {% if object.state == 'working' %}
                        {{ form.done_work.errors }}
                        {{ form.done_work }}
                        <div id="jobs"></div>
                    {% else %}
                        <table id="jobs-form" class="readable">
                            <thead>
                                <tr>
                                    <th>Работа</th><th>Цена</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for row in object.done_work %}
                                    <tr>
                                        <td class="col-title">{{ row.title }}</td>
                                        <td class="col-price">{{ row.price|price }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td class="col-title">Сумма за ремонт:</td>
                                    <td class="col-price">{{ object.done_work_sum|price }}</td>
                                </tr>
                            </tfoot>
                        </table>
                    {% endif %}
                </div>
            </div>
            {# --------- #}

            {# SPARE PART #}
            <div class="module aligned panel panel-spare_part">
                <h2>Замененные детали</h2>
                <div class="form-row">
                    {% if object.state == 'working' %}
                        <div id="spare_part"></div>
                    {% else %}
                        <table id="spare_part-form" class="readable">
                            <thead>
                                <tr>
                                    <th>Деталь</th><th>Гарантия</th><th>Цена</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for row in object.spare_part_counts.all %}
                                    <tr>
                                        <td class="col-title">{{ row.title }}</td>
                                        <td class="col-guarantee">{{ row.guarantee.title }}</td>
                                        <td class="col-price">{{ row.retail_price|price }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td class="col-title" colspan="2">Сумма за запчасти:</td>
                                    <td class="col-price">{{ object.spare_part_sum|price }}</td>
                                </tr>
                            </tfoot>
                        </table>
                    {% endif %}
                </div>
            </div>
            {# --------- #}
        </div>
    </div>

    {% with object.available_transitions as transitions %}
        {% if transitions %}
            <div class="action-panel">
                {% if 'repair' in transitions %}
                    <button type="submit" name="transition" value="repair">В ремонт</button>
                {% endif %}

                {% if 'wait_agree' in transitions %}
                    <button type="submit" name="transition" value="wait_agree">Согласовать</button>
                {% endif %}

                {% if 'wait_parts' in transitions %}
                    <button type="submit" name="transition" value="wait_parts">Ждать запчасти</button>
                {% endif %}

                {% if 'reject' in transitions %}
                    <button type="submit" name="transition" value="reject">Без ремонта</button>
                {% endif %}

                {% if 'ready' in transitions %}
                    <span class="action-separator"></span>
                    <button type="submit" name="transition" value="ready">Готово</button>
                {% endif %}

                {% if 'close' in transitions %}
                    <span class="action-separator"></span>
                    <button type="submit" name="transition" value="close">Выдать</button>
                {% endif %}

                <button class="save" type="submit" name="save" value="_continue">Сохранить и продолжить</button>
            </div>
        {% endif %}
    {% endwith %}
    {{ form.media }}
    {% if object.state == 'working' %}
        {% javascript 'marionette' %}
        {% javascript 'crm_app' %}
    {% endif %}
    </form>
{% endblock %}

service_plus/apps/crm/templates/crm/admin/state_filter.html
{% load i18n %}
<h3>{% blocktrans with filter_title=title %} By {{ filter_title }} {% endblocktrans %}</h3>
<ul class="state-filters">
{% for choice in choices %}
    <li{% if choice.selected %} class="selected"{% endif %}>
    <a href="{{ choice.query_string|iriencode }}"><span class="{{ choice.query_string|cut:'?'|cut:'state__exact=' }}"></span>{{ choice.display }}</a></li>
{% endfor %}
</ul>